# fly.toml app configuration file generated for sourcebot on 2024-09-06T11:03:58-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sourcebot'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '32gb'
  cpu_kind = 'shared'
  cpus = 2

[mounts]
  source = "sourcebot_data"
  destination = "/data"
  initial_size = "30GB"
