contact_links:
  - name: ðŸ’¡ Feature Request
    url: https://github.com/sourcebot-dev/sourcebot/discussions/new?category=ideas
    about: Suggest any ideas you have using our discussion forums.
  - name: ðŸ›Ÿ Get Help
    url: https://github.com/sourcebot-dev/sourcebot/discussions/new?category=support
    about: If you can't get something to work the way you expect, open a question in our discussion forums.